// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "app": {
    "/": {
      "metadata": {
        "title": "Create Next App",
        "description": "Generated by create next app"
      },
      "loading": {
        "ariaLabel": "loading..."
      },
      "not-found": {
        "title": "Nothing to see here",
        "description": "Page you are trying to open does not exist. You may have mistyped the address, or the page has been moved to another URL. If you think this is an error contact support.",
        "homeButtonLabel": "Home",
        "contactSupport": "Contact Support",
        "goBackButtonLabel": "Go back",
        "needHelp": "Need help"
      },
      "error": {
        "title": "Something bad just happened...",
        "description": "We encountered an unexpected error. Please try again or contact support if the problem persists.",
        "homeButtonLabel": "Home",
        "contactSupport": "Contact Support",
        "needHelp": "Need help",
        "tryAgainButtonLabel": "Try Again"
      },
      "page": {
        "HeroSection": {
          "h1": "Next Js Template"
        }
      },
      "layout": {
        "SiteHeader": {
          "links": {
            "blogs": "blogs",
            "blogExample": "blog example",
            "admin": "admin"
          }
        }
      }
    },
    "/[locale]/blogs": {
      "page": {
        "BlogsSection": {
          "title": "Blog Posts",
          "description": "Discover the latest trends, tips, and best practices in modern web development. From UI components to design systems, stay updated with our expert insights."
        }
      }
    }
  },
  "components": {
    "utils": {
      "MdxRemoteServer": {
        "tableOfContents": "Table of contents"
      }
    },
    "ThemeToggle": {
      "srOnlyLabel": "Toggle theme"
    }
  }
};
export default messages;