// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "app": {
    "/": {
      "metadata": {
        "title": "Create Next App",
        "description": "Generated by create next app"
      },
      "clickMeButtonLabel": "click me"
    }
  }
};
export default messages;