import { validateAndSetLocale } from "@/i18n/utils/validateLocale";
import Providers from "@/providers/Providers";
import type { Metadata } from "next";
import localFont from "next/font/local";

const inter = localFont({
  src: "../../assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-sans",
});

const geistSans = localFont({
  src: "../../assets/fonts/Geist/Geist-VariableFont_wght.ttf",
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: "../../assets/fonts/Geist_Mono/GeistMono-VariableFont_wght.ttf",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
  params,
}: LayoutProps<"/[locale]">) {
  const { locale } = await params;

  const validatedLocale = validateAndSetLocale(locale);

  return (
    <html
      lang={validatedLocale}
      className={inter.variable}
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-w-87.5 antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
