import { validateAndSetLocale } from "@/i18n/utils/validateLocale";
import Providers from "@/providers/Providers";
import type { Metadata } from "next";
import localFont from "next/font/local";

const inter = localFont({
  src: "../../assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-sans",
});

const geistMono = localFont({
  src: "../../assets/fonts/Geist_Mono/GeistMono-VariableFont_wght.ttf",
  variable: "--font-geist-mono",
});

const vazirmatn = localFont({
  src: "../../assets/fonts/Vazirmatn/Vazirmatn-VariableFont_wght.ttf",
  variable: "--font-vazirmatn",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
  params,
}: LayoutProps<"/[locale]">) {
  const { locale } = await params;

  const validatedLocale = validateAndSetLocale(locale);

  const font = validatedLocale === "ar" ? vazirmatn : inter;
  const fontMono = validatedLocale === "ar" ? vazirmatn : geistMono;

  return (
    <html
      dir={validatedLocale === "ar" ? "rtl" : "ltr"}
      lang={validatedLocale}
      className={font.variable}
      data-scroll-behavior="smooth"
      suppressHydrationWarning
    >
      <body className={`${fontMono.variable} min-w-87.5 antialiased`} id="body">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
